# Site settings
title: "Bagpipe music"
description: ""
baseurl: "/bagpipe-music"
url: "https://glascode.github.io"

# Build settings
include: ["_pages"]  # include more files
defaults:
  - scope:
      path: "archive"
    values:
      pdf: true
kramdown:
  input: GFM
